# Generated by Django 4.0.4 on 2022-05-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0004_alter_student_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, default='media/IMG_0499.JPG/', null=True, upload_to='media/'),
        ),
    ]
