# Generated by Django 4.0.4 on 2022-05-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0006_student_year_in_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.BooleanField(default='hello'),
            preserve_default=False,
        ),
    ]
