# Generated by Django 4.0.4 on 2022-05-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0008_alter_student_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='active',
        ),
    ]
