# Generated by Django 4.0.4 on 2022-05-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0003_alter_student_options_alter_student_first_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Ögrenciler'},
        ),
    ]
