# Generated by Django 4.0.5 on 2022-06-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, default='defaults/default.jpg', null=True, upload_to='product/'),
        ),
    ]
